# Generated by Django 4.2.16 on 2024-09-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_high_f', models.FloatField()),
                ('temp_avg_f', models.FloatField()),
                ('temp_low_f', models.FloatField()),
                ('dew_point_high_f', models.FloatField()),
                ('dew_point_avg_f', models.FloatField()),
                ('dew_point_low_f', models.FloatField()),
                ('humidity_high_percent', models.FloatField()),
                ('humidity_avg_percent', models.FloatField()),
                ('humidity_low_percent', models.FloatField()),
                ('sea_level_pressure_high_inches', models.FloatField()),
                ('sea_level_pressure_avg_inches', models.FloatField()),
                ('sea_level_pressure_low_inches', models.FloatField()),
                ('visibility_high_miles', models.FloatField()),
                ('visibility_avg_miles', models.FloatField()),
                ('visibility_low_miles', models.FloatField()),
                ('wind_high_mph', models.FloatField()),
                ('wind_avg_mph', models.FloatField()),
                ('wind_gust_mph', models.FloatField()),
                ('precipitation_sum_inches', models.FloatField()),
                ('events', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
