# Generated by Django 4.2.11 on 2024-09-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='api_url',
            field=models.URLField(verbose_name={'max_length': 60, 'min_length': 15}),
        ),
    ]
